---
title: "Reproducible Research: Peer Assessment 1"
author: Thomas Fetcke
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
library(dplyr,warn.conflicts=FALSE)
library(lubridate)
library(lattice)
dataFile="activity.csv"
if (!file.exists(dataFile))
    unzip("activity.zip")
activity <- tbl_df(read.csv(dataFile))
```

## What is the mean total number of steps taken per day?

```{r}
steps_by_day <- activity %>% 
    group_by(date) %>% 
    summarise(total=sum(steps, na.rm=TRUE))
histogram(~ total, data=steps_by_day, breaks=23, type="count",
          main="Total Number of Steps Taken per Day",
          xlab="Number of steps", ylab="Frequency (number of days)")
```

```{r}
daily_avg <- steps_by_day %>% 
    summarise(mean=mean(total), median=median(total))
daily_avg
```

## What is the average daily activity pattern?

```{r}
steps_by_interval <- activity %>%
    group_by(interval) %>%
    summarise(avg=mean(steps, na.rm=TRUE))
xyplot(avg ~ interval, data=steps_by_interval, type="l",
       main="Average Number of Steps by Interval",
       xlab="Interval", ylab="Number of steps")
```

```{r}
steps_by_interval %>% filter(avg == max(avg))
```


## Imputing missing values

```{r}
activity %>% tally(is.na(steps))
```

```{r}
imputed <- activity %>% 
    group_by(interval) %>% 
    mutate(steps=replace(steps, is.na(steps), round(mean(steps, na.rm=TRUE))))
```

```{r}
steps_by_day <- imputed %>% 
    group_by(date) %>% 
    summarise(total=sum(steps, na.rm=TRUE))
histogram(~ total, data=steps_by_day, breaks=23, type="count",
          main="Total Number of Steps Taken per Day",
          xlab="Number of steps", ylab="Frequency (number of days)")
```

```{r}
daily_avg <- steps_by_day %>% 
    summarise(mean=mean(total), median=median(total))
daily_avg
```



## Are there differences in activity patterns between weekdays and weekends?

```{r}
steps_by_interval_day <- imputed %>%
    mutate(day=as.factor(ifelse(wday(date) %in% 2:6, 
                                "weekday", "weekend"))) %>%
    group_by(day, interval) %>%
    summarize(avg=mean(steps))
xyplot(avg ~ interval | day, data=steps_by_interval_day, 
       layout=c(1,2), type="l",
       main="Average Number of Steps by Interval And Type of Day",
       xlab="Interval", ylab="Number of steps")
```
